# SHARED=ON, BUILD_DEPENDENCY_FROM_SOURCE=ON

language: generic # optional, just removes the language badge
env:
    global:
        - SHARED = OFF
        - BUILD_DEPENDENCY_FROM_SOURCE = ON
notifications:
    email:
        on_success: never
        on_failure: always
matrix:
    include:
        - os: linux
          dist: bionic
          sudo: true
          language: python
          python: "3.6"
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - cmake
         env: BUILD_DEPENDENCY_FROM_SOURCE=ON
         before_install: ./util/scripts/setup-linux.sh
         script: ./util/scripts/run-travis.sh
          
                
